### ISSUE TITLE
Support live tests

### ISSUE THREAD

**Issue by heaths** [heaths/azcrypto#14]
- [ ] Use idiomatic approach to live testing using test categories.
- [ ] Figure out how to set env vars from `azd` output; could potentially use `godotenv` to scan for an read in generated .env files. @ellismg is that was is intended, or some other way of setting env vars e.g., hypothetical `eval(azd env show)` or whatever is appropriate for your current shell where the CLI, like some others, automatically detects the parent shell or it can be specified to override / if not detected?

**Comment by ellismg** [comment]
We have `azd env get-values` and `azd env get-values --output=json` which can give you this information, but we aren't slick enough to give you a format based on your current shell so you could just eval it.
